### ISSUE TITLE
ImportError: No module named pcf

### ISSUE THREAD

**Issue by h908714124** [tomasmcz/imago#7]
I get an import error, how to install pcf?

```
$ ./imago
Traceback (most recent call last):
  File "./imago", line 5, in <module>
    from src import imago
  File "$/workspace/imago/src/imago.py", line 17, in <module>
    import linef
  File "$/workspace/imago/src/linef.py", line 13, in <module>
    import filters
  File "$/workspace/imago/src/filters.py", line 10, in <module>
    import pcf
ImportError: No module named pcf

```

**Comment by h908714124** [comment]
had to run `make` first
